version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio-website
    ports:
      - "80:8000"
    environment:
      - FLASK_ENV=production
      - PORT=8000
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - CONTACT_EMAIL=${CONTACT_EMAIL:-contact@saivikas.work}
    volumes:
      - ./data:/app/data:ro
      - ./public/assets:/app/public/assets:ro
    restart: unless-stopped
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Example: Live project 1
  # project1:
  #   image: your-project1:latest
  #   container_name: project1
  #   ports:
  #     - "8001:8000"
  #   restart: unless-stopped
  #   networks:
  #     - portfolio-network

  # Example: Live project 2
  # project2:
  #   image: your-project2:latest
  #   container_name: project2
  #   ports:
  #     - "8002:8000"
  #   restart: unless-stopped
  #   networks:
  #     - portfolio-network

  # Example: Live project 3
  # project3:
  #   image: your-project3:latest
  #   container_name: project3
  #   ports:
  #     - "8003:8000"
  #   restart: unless-stopped
  #   networks:
  #     - portfolio-network

  # Optional: Nginx reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - portfolio
  #   restart: unless-stopped
  #   networks:
  #     - portfolio-network

networks:
  portfolio-network:
    driver: bridge
